additionalRepositories:
  - url: https://github.com/mattermost/mattermost

ports:
  - port: 8065
    description: for Mattermost instance
    onOpen: open-browser
    visibility: public
  - port: 9000
    description: for Mattermost + Gitpod welcome message
    onOpen: open-browser
    visibility: public
  - port: 6080
    description: for noVNC instance (Cypress)
    onOpen: notify
  - port: 5432
    onOpen: ignore
  - port: 5900
    onOpen: ignore
  - port: 9000
    onOpen: ignore

image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true
    pullRequests: true
    addCheck: false

vscode:
  extensions:
    - golang.go

workspaceLocation: mattermost-gitpod-config/mattermost.code-workspace

tasks:
  - name: Server
    before: |
  - name: Welcome
    init: |
      npm i -g markserv
    command: |
      markserv -p 9000 &
      gp preview "$(gp url 9000)/welcome.md"
      exit
      export MM_SERVICESETTINGS_SITEURL=$(gp url 8065)
    init: |
      go run ./build/docker-compose-generator/main.go postgres minio | docker-compose -f docker-compose.makefile.yml pull
      make run-server
      gp ports await 8065
      make stop-server
      make test-data
      echo "Server built"
    command: |
      make run-server
    env:
      ENABLED_DOCKER_SERVICES: postgres minio
      MM_SERVICESETTINGS_ENABLELOCALMODE: true
      MM_SERVICESETTINGS_ENABLEBOTACCOUNTCREATION: true
      MM_SERVICESETTINGS_ENABLEOAUTHSERVICEPROVIDER: true
      MM_SERVICESETTINGS_ENABLEDEVELOPER: true
      MM_SERVICESETTINGS_ENABLETESTING: true
      MM_TEAMSETTINGS_ENABLEOPENSERVER: true
      MM_PLUGINSETTINGS_AUTOMATICPREPACKAGEDPLUGINS: true
      MM_PLUGINSETTINGS_ENABLEUPLOADS: true
      MM_EXPERIMENTALSETTINGS_ENABLEAPPBAR: true
      MM_FEATUREFLAGS_AppsEnabled: true
      MM_LOGSETTINGS_CONSOLELEVEL: DEBUG
      MM_LOGSETTINGS_FILELEVEL: DEBUG

  - name: Webapp
    before: |
      cd ../mattermost/webapp
      export MM_SERVICESETTINGS_SITEURL=$(gp url 8065)
      nvm install
      nvm alias default $(cat .nvmrc)
      echo "nvm use default" >> ~/.bashrc
    init: |
      mkdir -p channels/dist
      cd ../server
      ln -nfs ../webapp/channels/dist client
      cd ../webapp
      npm i
      echo "Webapp built"
    command: |
      npm i
      make run
    openMode: split-right

  - name: Cypress
    init: |
      cd ../mattermost/e2e-tests/cypress
      npm i

  - name: Playwright
    init: |
      cd ../mattermost/e2e-tests/playwright
      npm i
      npx playwright install

  - name: Plugin
    before: |
      nvm install || nvm install v13.14
    init: |
      source /workspace/mattermost-gitpod-config/scripts/plugin/init-plugin-project.sh
      echo "Plugin built"
    command: |
      gp ports await 8065
      echo "Server is running at $(gp url 8065)"
      source /workspace/mattermost-gitpod-config/scripts/plugin/run-plugin-project.sh
    env:
      MM_SERVICESETTINGS_ENABLEDEVELOPER: true

  - name: Project
    init: |
      source /workspace/mattermost-gitpod-config/scripts/app/init-app-project.sh
      echo "Project built"
    command: |
      source /workspace/mattermost-gitpod-config/scripts/app/run-app-project.sh
