additionalRepositories:
  - url: https://github.com/mattermost/mattermost-server
  - url: https://github.com/mattermost/mattermost-webapp

ports:
  - port: 8065
    onOpen: open-browser

image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true
    pullRequests: true

vscode:
  extensions:
    - golang.go

workspaceLocation:
  mattermost-gitpod-config/mattermost.code-workspace

tasks:
  - name: Server
    before: |
      cd ../mattermost-server
      export MM_SERVICESETTINGS_SITEURL=$(gp url 8065)
    init: |
      go run ./build/docker-compose-generator/main.go postgres minio | docker-compose -f docker-compose.makefile.yml pull
      go run ./build/docker-compose-generator/main.go postgres minio | docker-compose -f docker-compose.makefile.yml -f /dev/stdin run -T --rm start_dependencies
      make run-server MM_NO_DOCKER=true
      gp await-port 8065
      make stop-server
      go run ./build/docker-compose-generator/main.go postgres minio | docker-compose -f docker-compose.makefile.yml -f /dev/stdin stop

    command: |
      export MM_SERVICESETTINGS_SITEURL=$(gp url 8065)
      go run ./build/docker-compose-generator/main.go postgres minio | docker-compose -f docker-compose.makefile.yml -f /dev/stdin run -T --rm start_dependencies
      make run-server MM_NO_DOCKER=true
    env:
      ENABLED_DOCKER_SERVICES: postgres minio
      MM_SERVICESETTINGS_ENABLELOCALMODE: true
      MM_SERVICESETTINGS_ENABLEBOTACCOUNTCREATION: true
      MM_SERVICESETTINGS_ENABLEOAUTHSERVICEPROVIDER: true
      MM_SERVICESETTINGS_ENABLEDEVELOPER: true
      MM_SERVICESETTINGS_ENABLETESTING: true
      MM_PLUGINSETTINGS_AUTOMATICPREPACKAGEDPLUGINS: true
      MM_PLUGINSETTINGS_ENABLEUPLOADS: true
      MM_FEATUREFLAGS_AppsEnabled: true
      MM_FEATUREFLAGS_AppBarEnabled: true
      MM_LOGSETTINGS_CONSOLELEVEL: DEBUG
      MM_LOGSETTINGS_FILELEVEL: DEBUG

  - name: Webapp
    before: |
      cd ../mattermost-webapp
      export MM_SERVICESETTINGS_SITEURL=$(gp url 8065)
    init: |
      mkdir dist
      cd ../mattermost-server
      ln -nfs ../mattermost-webapp/dist client
      cd ../mattermost-webapp

      nvm install v16.4.0
      nvm alias default v16.4.0
      npm i
      make build
    command: |
      nvm use v16.4.0
      npm i
      make run
    openMode: split-right

  - name: Plugin
    init: |
      source /workspace/mattermost-gitpod-config/scripts/plugin/init-plugin-project.sh
    command: |
      gp await-port 8065
      echo "Server is running at $(gp url 8065)"
      source /workspace/mattermost-gitpod-config/scripts/plugin/run-plugin-project.sh
    env:
      MM_SERVICESETTINGS_ENABLEDEVELOPER: true

  - name: App
    init: |
      source /workspace/mattermost-gitpod-config/scripts/app/init-app-project.sh
    command: |
      source /workspace/mattermost-gitpod-config/scripts/app/run-app-project.sh
